### ISSUE TITLE
auto install tensorflow-probability 0.9.0 but requires 0.8.0

### ISSUE THREAD

**Issue by leomichalski** [tensorflow/kfac#35]
I solved it by uninstalling tensorflow-probability==0.9.0 and installing 0.8.0.

Observation: My TensorFlow version is 1.15.

$ pip install kfac
```
Collecting kfac
  Downloading kfac-0.2.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 683 kB/s 
Collecting tensorflow-probability
  Downloading tensorflow_probability-0.9.0-py2.py3-none-any.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 47 kB/s 
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from kfac) (1.14.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from kfac) (1.18.1)
Requirement already satisfied: decorator in /opt/conda/lib/python3.7/site-packages (from tensorflow-probability->kfac) (4.4.2)
Requirement already satisfied: gast>=0.2 in /opt/conda/lib/python3.7/site-packages (from tensorflow-probability->kfac) (0.2.2)
Requirement already satisfied: cloudpickle>=1.2.2 in /opt/conda/lib/python3.7/site-packages (from tensorflow-probability->kfac) (1.3.0)
Installing collected packages: tensorflow-probability, kfac
Successfully installed kfac-0.2.0 tensorflow-probability-0.9.0
```
>>> import kfac
```
WARNING:tensorflow:From /opt/conda/lib/python3.7/site-packages/kfac/python/ops/utils.py:38: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/kfac/__init__.py", line 22, in <module>
    from kfac.python import keras
  File "/opt/conda/lib/python3.7/site-packages/kfac/python/keras/__init__.py", line 18, in <module>
    from kfac.python.keras import optimizers
  File "/opt/conda/lib/python3.7/site-packages/kfac/python/keras/optimizers.py", line 28, in <module>
    from kfac.python.keras import utils
  File "/opt/conda/lib/python3.7/site-packages/kfac/python/keras/utils.py", line 24, in <module>
    from kfac.python.ops import layer_collection as kfac_layer_collection
  File "/opt/conda/lib/python3.7/site-packages/kfac/python/ops/layer_collection.py", line 79, in <module>
    from kfac.python.ops import loss_functions as lf
  File "/opt/conda/lib/python3.7/site-packages/kfac/python/ops/loss_functions.py", line 26, in <module>
    import tensorflow_probability as tfp
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_probability/__init__.py", line 68, in <module>
    _ensure_tf_install()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_probability/__init__.py", line 65, in _ensure_tf_install
    present=tf.__version__))
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.1; Detected an installation of version 1.15.0. Please upgrade TensorFlow to proceed.
```

**Comment by StaelTchinda** [comment]
I have the exact same problem. Did you manage to solve it @leomichalski ?

**Comment by leomichalski** [comment]
Does running "pip install tensorflow-probability==0.8" after installing kfac works for you?

**Comment by StaelTchinda** [comment]
Yes, it did. Thank you.
I hope it will not cause further problems later.
